language: node_js
node_js: node
deploy:
  provider: heroku
  # Warning: token will expire 09/22/2019
  api_key:
    secure: V34EQzEL/GmIjU2MKmQF/3FNGD8i9ON3gu+Mh0m35H5hmej7coapSwW4lscWdV+2Lo7d0T28f+RWYOMk1OIdRCS0Ygux0hP06BRYzGiv+IDU8o6thR+15729TpjoXqXFtbd4k+mc74yEG1pF3NK3dy9RN+jXucgPPDi3di50vy7M29Ltl/Y0AoKr5nEVfBVqemBLI4kcp+9rFLalxz0jeJ+mTJTobm34uyfmllX1EU6tPpyaAgbls2zwIz82PcoPwEkayFe/x7uD6kxJk7xpkbdRATPZpV428839u8MTujtGZwXJZwWwZ0p5fVwxqMvLdjqAddo7Blg476wrbhZHLsqEJ+N06W2bj6npyxCeOJQ6fbw6ToWxQEntKEjnufnfabSqM5dB+wtIKJ+Ga7BMiin+GvjxY55fhmtZ53wUdjQsPswuYHqGtUozyOVfZhOqObH1vEzrm4j4OlUob3/OnCZn63PXLXCrf+ERCkEWOY3UDkWCOHl1UcHZ6IOC6fDRMOJLrWuWnN3UYxAzp+Qm1Gd1lbLdBKBHZ88vvEZk+n+bWv9wn0nZkZ1Sf5T0clORoyubdPC+fXMnfO6S0RcV6DR1mDUeRZaQeBl7LpW7jNcgfqyx6UbN4RcURGiIRbUejB6GmJUMzvtnBUETHzyRd/3QsyuBva90tsxtZjxcR/Y=
  app: mysterious-garden-22421
  on:
    repo: richigro/node-shopping-list-integration-tests
